package com.myqq.entity;

import java.util.ArrayList;
import java.util.List;

public class manyDayExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table many_day
     *
    
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table many_day
     *
    
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table many_day
     *
    
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table many_day
     *
    
     */
    public manyDayExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table many_day
     *
    
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table many_day
     *
    
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table many_day
     *
    
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table many_day
     *
    
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table many_day
     *
    
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table many_day
     *
    
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table many_day
     *
    
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table many_day
     *
    
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table many_day
     *
    
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table many_day
     *
    
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table many_day
     *
    
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDayCountIsNull() {
            addCriterion("day_count is null");
            return (Criteria) this;
        }

        public Criteria andDayCountIsNotNull() {
            addCriterion("day_count is not null");
            return (Criteria) this;
        }

        public Criteria andDayCountEqualTo(Integer value) {
            addCriterion("day_count =", value, "dayCount");
            return (Criteria) this;
        }

        public Criteria andDayCountNotEqualTo(Integer value) {
            addCriterion("day_count <>", value, "dayCount");
            return (Criteria) this;
        }

        public Criteria andDayCountGreaterThan(Integer value) {
            addCriterion("day_count >", value, "dayCount");
            return (Criteria) this;
        }

        public Criteria andDayCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("day_count >=", value, "dayCount");
            return (Criteria) this;
        }

        public Criteria andDayCountLessThan(Integer value) {
            addCriterion("day_count <", value, "dayCount");
            return (Criteria) this;
        }

        public Criteria andDayCountLessThanOrEqualTo(Integer value) {
            addCriterion("day_count <=", value, "dayCount");
            return (Criteria) this;
        }

        public Criteria andDayCountIn(List<Integer> values) {
            addCriterion("day_count in", values, "dayCount");
            return (Criteria) this;
        }

        public Criteria andDayCountNotIn(List<Integer> values) {
            addCriterion("day_count not in", values, "dayCount");
            return (Criteria) this;
        }

        public Criteria andDayCountBetween(Integer value1, Integer value2) {
            addCriterion("day_count between", value1, value2, "dayCount");
            return (Criteria) this;
        }

        public Criteria andDayCountNotBetween(Integer value1, Integer value2) {
            addCriterion("day_count not between", value1, value2, "dayCount");
            return (Criteria) this;
        }

        public Criteria andWeekNameIsNull() {
            addCriterion("week_name is null");
            return (Criteria) this;
        }

        public Criteria andWeekNameIsNotNull() {
            addCriterion("week_name is not null");
            return (Criteria) this;
        }

        public Criteria andWeekNameEqualTo(String value) {
            addCriterion("week_name =", value, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameNotEqualTo(String value) {
            addCriterion("week_name <>", value, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameGreaterThan(String value) {
            addCriterion("week_name >", value, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameGreaterThanOrEqualTo(String value) {
            addCriterion("week_name >=", value, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameLessThan(String value) {
            addCriterion("week_name <", value, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameLessThanOrEqualTo(String value) {
            addCriterion("week_name <=", value, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameLike(String value) {
            addCriterion("week_name like", value, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameNotLike(String value) {
            addCriterion("week_name not like", value, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameIn(List<String> values) {
            addCriterion("week_name in", values, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameNotIn(List<String> values) {
            addCriterion("week_name not in", values, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameBetween(String value1, String value2) {
            addCriterion("week_name between", value1, value2, "weekName");
            return (Criteria) this;
        }

        public Criteria andWeekNameNotBetween(String value1, String value2) {
            addCriterion("week_name not between", value1, value2, "weekName");
            return (Criteria) this;
        }

        public Criteria andNewVisitIsNull() {
            addCriterion("new_visit is null");
            return (Criteria) this;
        }

        public Criteria andNewVisitIsNotNull() {
            addCriterion("new_visit is not null");
            return (Criteria) this;
        }

        public Criteria andNewVisitEqualTo(Integer value) {
            addCriterion("new_visit =", value, "newVisit");
            return (Criteria) this;
        }

        public Criteria andNewVisitNotEqualTo(Integer value) {
            addCriterion("new_visit <>", value, "newVisit");
            return (Criteria) this;
        }

        public Criteria andNewVisitGreaterThan(Integer value) {
            addCriterion("new_visit >", value, "newVisit");
            return (Criteria) this;
        }

        public Criteria andNewVisitGreaterThanOrEqualTo(Integer value) {
            addCriterion("new_visit >=", value, "newVisit");
            return (Criteria) this;
        }

        public Criteria andNewVisitLessThan(Integer value) {
            addCriterion("new_visit <", value, "newVisit");
            return (Criteria) this;
        }

        public Criteria andNewVisitLessThanOrEqualTo(Integer value) {
            addCriterion("new_visit <=", value, "newVisit");
            return (Criteria) this;
        }

        public Criteria andNewVisitIn(List<Integer> values) {
            addCriterion("new_visit in", values, "newVisit");
            return (Criteria) this;
        }

        public Criteria andNewVisitNotIn(List<Integer> values) {
            addCriterion("new_visit not in", values, "newVisit");
            return (Criteria) this;
        }

        public Criteria andNewVisitBetween(Integer value1, Integer value2) {
            addCriterion("new_visit between", value1, value2, "newVisit");
            return (Criteria) this;
        }

        public Criteria andNewVisitNotBetween(Integer value1, Integer value2) {
            addCriterion("new_visit not between", value1, value2, "newVisit");
            return (Criteria) this;
        }

        public Criteria andOldVisitIsNull() {
            addCriterion("old_visit is null");
            return (Criteria) this;
        }

        public Criteria andOldVisitIsNotNull() {
            addCriterion("old_visit is not null");
            return (Criteria) this;
        }

        public Criteria andOldVisitEqualTo(Integer value) {
            addCriterion("old_visit =", value, "oldVisit");
            return (Criteria) this;
        }

        public Criteria andOldVisitNotEqualTo(Integer value) {
            addCriterion("old_visit <>", value, "oldVisit");
            return (Criteria) this;
        }

        public Criteria andOldVisitGreaterThan(Integer value) {
            addCriterion("old_visit >", value, "oldVisit");
            return (Criteria) this;
        }

        public Criteria andOldVisitGreaterThanOrEqualTo(Integer value) {
            addCriterion("old_visit >=", value, "oldVisit");
            return (Criteria) this;
        }

        public Criteria andOldVisitLessThan(Integer value) {
            addCriterion("old_visit <", value, "oldVisit");
            return (Criteria) this;
        }

        public Criteria andOldVisitLessThanOrEqualTo(Integer value) {
            addCriterion("old_visit <=", value, "oldVisit");
            return (Criteria) this;
        }

        public Criteria andOldVisitIn(List<Integer> values) {
            addCriterion("old_visit in", values, "oldVisit");
            return (Criteria) this;
        }

        public Criteria andOldVisitNotIn(List<Integer> values) {
            addCriterion("old_visit not in", values, "oldVisit");
            return (Criteria) this;
        }

        public Criteria andOldVisitBetween(Integer value1, Integer value2) {
            addCriterion("old_visit between", value1, value2, "oldVisit");
            return (Criteria) this;
        }

        public Criteria andOldVisitNotBetween(Integer value1, Integer value2) {
            addCriterion("old_visit not between", value1, value2, "oldVisit");
            return (Criteria) this;
        }

        public Criteria andSessionCountIsNull() {
            addCriterion("session_count is null");
            return (Criteria) this;
        }

        public Criteria andSessionCountIsNotNull() {
            addCriterion("session_count is not null");
            return (Criteria) this;
        }

        public Criteria andSessionCountEqualTo(Integer value) {
            addCriterion("session_count =", value, "sessionCount");
            return (Criteria) this;
        }

        public Criteria andSessionCountNotEqualTo(Integer value) {
            addCriterion("session_count <>", value, "sessionCount");
            return (Criteria) this;
        }

        public Criteria andSessionCountGreaterThan(Integer value) {
            addCriterion("session_count >", value, "sessionCount");
            return (Criteria) this;
        }

        public Criteria andSessionCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("session_count >=", value, "sessionCount");
            return (Criteria) this;
        }

        public Criteria andSessionCountLessThan(Integer value) {
            addCriterion("session_count <", value, "sessionCount");
            return (Criteria) this;
        }

        public Criteria andSessionCountLessThanOrEqualTo(Integer value) {
            addCriterion("session_count <=", value, "sessionCount");
            return (Criteria) this;
        }

        public Criteria andSessionCountIn(List<Integer> values) {
            addCriterion("session_count in", values, "sessionCount");
            return (Criteria) this;
        }

        public Criteria andSessionCountNotIn(List<Integer> values) {
            addCriterion("session_count not in", values, "sessionCount");
            return (Criteria) this;
        }

        public Criteria andSessionCountBetween(Integer value1, Integer value2) {
            addCriterion("session_count between", value1, value2, "sessionCount");
            return (Criteria) this;
        }

        public Criteria andSessionCountNotBetween(Integer value1, Integer value2) {
            addCriterion("session_count not between", value1, value2, "sessionCount");
            return (Criteria) this;
        }

        public Criteria andOutRateIsNull() {
            addCriterion("out_rate is null");
            return (Criteria) this;
        }

        public Criteria andOutRateIsNotNull() {
            addCriterion("out_rate is not null");
            return (Criteria) this;
        }

        public Criteria andOutRateEqualTo(Double value) {
            addCriterion("out_rate =", value, "outRate");
            return (Criteria) this;
        }

        public Criteria andOutRateNotEqualTo(Double value) {
            addCriterion("out_rate <>", value, "outRate");
            return (Criteria) this;
        }

        public Criteria andOutRateGreaterThan(Double value) {
            addCriterion("out_rate >", value, "outRate");
            return (Criteria) this;
        }

        public Criteria andOutRateGreaterThanOrEqualTo(Double value) {
            addCriterion("out_rate >=", value, "outRate");
            return (Criteria) this;
        }

        public Criteria andOutRateLessThan(Double value) {
            addCriterion("out_rate <", value, "outRate");
            return (Criteria) this;
        }

        public Criteria andOutRateLessThanOrEqualTo(Double value) {
            addCriterion("out_rate <=", value, "outRate");
            return (Criteria) this;
        }

        public Criteria andOutRateIn(List<Double> values) {
            addCriterion("out_rate in", values, "outRate");
            return (Criteria) this;
        }

        public Criteria andOutRateNotIn(List<Double> values) {
            addCriterion("out_rate not in", values, "outRate");
            return (Criteria) this;
        }

        public Criteria andOutRateBetween(Double value1, Double value2) {
            addCriterion("out_rate between", value1, value2, "outRate");
            return (Criteria) this;
        }

        public Criteria andOutRateNotBetween(Double value1, Double value2) {
            addCriterion("out_rate not between", value1, value2, "outRate");
            return (Criteria) this;
        }

        public Criteria andVisitWebEverySessionIsNull() {
            addCriterion("visit_web_every_session is null");
            return (Criteria) this;
        }

        public Criteria andVisitWebEverySessionIsNotNull() {
            addCriterion("visit_web_every_session is not null");
            return (Criteria) this;
        }

        public Criteria andVisitWebEverySessionEqualTo(Double value) {
            addCriterion("visit_web_every_session =", value, "visitWebEverySession");
            return (Criteria) this;
        }

        public Criteria andVisitWebEverySessionNotEqualTo(Double value) {
            addCriterion("visit_web_every_session <>", value, "visitWebEverySession");
            return (Criteria) this;
        }

        public Criteria andVisitWebEverySessionGreaterThan(Double value) {
            addCriterion("visit_web_every_session >", value, "visitWebEverySession");
            return (Criteria) this;
        }

        public Criteria andVisitWebEverySessionGreaterThanOrEqualTo(Double value) {
            addCriterion("visit_web_every_session >=", value, "visitWebEverySession");
            return (Criteria) this;
        }

        public Criteria andVisitWebEverySessionLessThan(Double value) {
            addCriterion("visit_web_every_session <", value, "visitWebEverySession");
            return (Criteria) this;
        }

        public Criteria andVisitWebEverySessionLessThanOrEqualTo(Double value) {
            addCriterion("visit_web_every_session <=", value, "visitWebEverySession");
            return (Criteria) this;
        }

        public Criteria andVisitWebEverySessionIn(List<Double> values) {
            addCriterion("visit_web_every_session in", values, "visitWebEverySession");
            return (Criteria) this;
        }

        public Criteria andVisitWebEverySessionNotIn(List<Double> values) {
            addCriterion("visit_web_every_session not in", values, "visitWebEverySession");
            return (Criteria) this;
        }

        public Criteria andVisitWebEverySessionBetween(Double value1, Double value2) {
            addCriterion("visit_web_every_session between", value1, value2, "visitWebEverySession");
            return (Criteria) this;
        }

        public Criteria andVisitWebEverySessionNotBetween(Double value1, Double value2) {
            addCriterion("visit_web_every_session not between", value1, value2, "visitWebEverySession");
            return (Criteria) this;
        }

        public Criteria andEverySessionVisitTimeIsNull() {
            addCriterion("every_session_visit_time is null");
            return (Criteria) this;
        }

        public Criteria andEverySessionVisitTimeIsNotNull() {
            addCriterion("every_session_visit_time is not null");
            return (Criteria) this;
        }

        public Criteria andEverySessionVisitTimeEqualTo(Double value) {
            addCriterion("every_session_visit_time =", value, "everySessionVisitTime");
            return (Criteria) this;
        }

        public Criteria andEverySessionVisitTimeNotEqualTo(Double value) {
            addCriterion("every_session_visit_time <>", value, "everySessionVisitTime");
            return (Criteria) this;
        }

        public Criteria andEverySessionVisitTimeGreaterThan(Double value) {
            addCriterion("every_session_visit_time >", value, "everySessionVisitTime");
            return (Criteria) this;
        }

        public Criteria andEverySessionVisitTimeGreaterThanOrEqualTo(Double value) {
            addCriterion("every_session_visit_time >=", value, "everySessionVisitTime");
            return (Criteria) this;
        }

        public Criteria andEverySessionVisitTimeLessThan(Double value) {
            addCriterion("every_session_visit_time <", value, "everySessionVisitTime");
            return (Criteria) this;
        }

        public Criteria andEverySessionVisitTimeLessThanOrEqualTo(Double value) {
            addCriterion("every_session_visit_time <=", value, "everySessionVisitTime");
            return (Criteria) this;
        }

        public Criteria andEverySessionVisitTimeIn(List<Double> values) {
            addCriterion("every_session_visit_time in", values, "everySessionVisitTime");
            return (Criteria) this;
        }

        public Criteria andEverySessionVisitTimeNotIn(List<Double> values) {
            addCriterion("every_session_visit_time not in", values, "everySessionVisitTime");
            return (Criteria) this;
        }

        public Criteria andEverySessionVisitTimeBetween(Double value1, Double value2) {
            addCriterion("every_session_visit_time between", value1, value2, "everySessionVisitTime");
            return (Criteria) this;
        }

        public Criteria andEverySessionVisitTimeNotBetween(Double value1, Double value2) {
            addCriterion("every_session_visit_time not between", value1, value2, "everySessionVisitTime");
            return (Criteria) this;
        }

        public Criteria andTransferRateIsNull() {
            addCriterion("transfer_rate is null");
            return (Criteria) this;
        }

        public Criteria andTransferRateIsNotNull() {
            addCriterion("transfer_rate is not null");
            return (Criteria) this;
        }

        public Criteria andTransferRateEqualTo(Double value) {
            addCriterion("transfer_rate =", value, "transferRate");
            return (Criteria) this;
        }

        public Criteria andTransferRateNotEqualTo(Double value) {
            addCriterion("transfer_rate <>", value, "transferRate");
            return (Criteria) this;
        }

        public Criteria andTransferRateGreaterThan(Double value) {
            addCriterion("transfer_rate >", value, "transferRate");
            return (Criteria) this;
        }

        public Criteria andTransferRateGreaterThanOrEqualTo(Double value) {
            addCriterion("transfer_rate >=", value, "transferRate");
            return (Criteria) this;
        }

        public Criteria andTransferRateLessThan(Double value) {
            addCriterion("transfer_rate <", value, "transferRate");
            return (Criteria) this;
        }

        public Criteria andTransferRateLessThanOrEqualTo(Double value) {
            addCriterion("transfer_rate <=", value, "transferRate");
            return (Criteria) this;
        }

        public Criteria andTransferRateIn(List<Double> values) {
            addCriterion("transfer_rate in", values, "transferRate");
            return (Criteria) this;
        }

        public Criteria andTransferRateNotIn(List<Double> values) {
            addCriterion("transfer_rate not in", values, "transferRate");
            return (Criteria) this;
        }

        public Criteria andTransferRateBetween(Double value1, Double value2) {
            addCriterion("transfer_rate between", value1, value2, "transferRate");
            return (Criteria) this;
        }

        public Criteria andTransferRateNotBetween(Double value1, Double value2) {
            addCriterion("transfer_rate not between", value1, value2, "transferRate");
            return (Criteria) this;
        }

        public Criteria andTransferCountIsNull() {
            addCriterion("transfer_count is null");
            return (Criteria) this;
        }

        public Criteria andTransferCountIsNotNull() {
            addCriterion("transfer_count is not null");
            return (Criteria) this;
        }

        public Criteria andTransferCountEqualTo(Integer value) {
            addCriterion("transfer_count =", value, "transferCount");
            return (Criteria) this;
        }

        public Criteria andTransferCountNotEqualTo(Integer value) {
            addCriterion("transfer_count <>", value, "transferCount");
            return (Criteria) this;
        }

        public Criteria andTransferCountGreaterThan(Integer value) {
            addCriterion("transfer_count >", value, "transferCount");
            return (Criteria) this;
        }

        public Criteria andTransferCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("transfer_count >=", value, "transferCount");
            return (Criteria) this;
        }

        public Criteria andTransferCountLessThan(Integer value) {
            addCriterion("transfer_count <", value, "transferCount");
            return (Criteria) this;
        }

        public Criteria andTransferCountLessThanOrEqualTo(Integer value) {
            addCriterion("transfer_count <=", value, "transferCount");
            return (Criteria) this;
        }

        public Criteria andTransferCountIn(List<Integer> values) {
            addCriterion("transfer_count in", values, "transferCount");
            return (Criteria) this;
        }

        public Criteria andTransferCountNotIn(List<Integer> values) {
            addCriterion("transfer_count not in", values, "transferCount");
            return (Criteria) this;
        }

        public Criteria andTransferCountBetween(Integer value1, Integer value2) {
            addCriterion("transfer_count between", value1, value2, "transferCount");
            return (Criteria) this;
        }

        public Criteria andTransferCountNotBetween(Integer value1, Integer value2) {
            addCriterion("transfer_count not between", value1, value2, "transferCount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table many_day
     *
     do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table many_day
     *
    
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}