package com.myqq.dao.mappers.page;

import com.myqq.entity.page.PageMain;
import com.myqq.entity.page.PageMainExample;
import java.util.List;

public interface PageMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_main
     *
    
     */
    long countByExample(PageMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_main
     *
    
     */
    int deleteByPrimaryKey(Integer pageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_main
     *
    
     */
    int insertId(PageMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_main
     *
    
     */
    int insertSelective(PageMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_main
     *
    
     */
    List<PageMain> selectByExample(PageMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_main
     *
    
     */
    PageMain selectByPrimaryKey(Integer pageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_main
     *
    
     */
    int updateByPrimaryKeySelective(PageMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_main
     *
    
     */
    int updateByPrimaryKey(PageMain record);
}