package com.myqq.dao.mappers;

import com.myqq.entity.manyDay;
import com.myqq.entity.manyDayExample;
import java.util.List;

public interface manyDayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table many_day
     *
    
     */
    long countByExample(manyDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table many_day
     *
    
     */
    int insert(manyDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table many_day
     *
    
     */
    int insertSelective(manyDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table many_day
     *
    
     */
    List<manyDay> selectByExample(manyDayExample example);
}