package com.myqq.dao.mappers;

import com.myqq.entity.MyDevice;

public interface MyDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_device
     *
    
     */
    int deleteByPrimaryKey(Integer deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_device
     *
    
     */
    int insert(MyDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_device
     *
    
     */
    int insertSelective(MyDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_device
     *
    
     */
    MyDevice selectByPrimaryKey(Integer deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_device
     *
    
     */
    int updateByPrimaryKeySelective(MyDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_device
     *
    
     */
    int updateByPrimaryKey(MyDevice record);
}