package com.myqq.dao.mappers;

import com.myqq.entity.sevenDay;
import com.myqq.entity.sevenDayExample;
import java.util.List;

public interface sevenDayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seven_day
     *
    
     */
    long countByExample(sevenDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seven_day
     *
    
     */
    int insert(sevenDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seven_day
     *
    
     */
    int insertSelective(sevenDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seven_day
     *
    
     */
    List<sevenDay> selectByExample(sevenDayExample example);
}