package com.myqq.dao.mappers;

import com.myqq.entity.twoHour;
import com.myqq.entity.twoHourExample;
import java.util.List;

public interface twoHourMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table two_hour
     *
    
     */
    long countByExample(twoHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table two_hour
     *
    
     */
    int insert(twoHour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table two_hour
     *
    
     */
    int insertSelective(twoHour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table two_hour
     *
    
     */
    List<twoHour> selectByExample(twoHourExample example);
}