package com.myqq.entity.page;

import java.util.ArrayList;
import java.util.List;

public class PageChildExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table page_child
     *
    
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table page_child
     *
    
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table page_child
     *
    
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_child
     *
    
     */
    public PageChildExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_child
     *
    
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_child
     *
    
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_child
     *
    
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_child
     *
    
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_child
     *
    
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_child
     *
    
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_child
     *
    
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_child
     *
    
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_child
     *
    
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_child
     *
    
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table page_child
     *
    
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPageChildIdIsNull() {
            addCriterion("page_child_id is null");
            return (Criteria) this;
        }

        public Criteria andPageChildIdIsNotNull() {
            addCriterion("page_child_id is not null");
            return (Criteria) this;
        }

        public Criteria andPageChildIdEqualTo(Integer value) {
            addCriterion("page_child_id =", value, "pageChildId");
            return (Criteria) this;
        }

        public Criteria andPageChildIdNotEqualTo(Integer value) {
            addCriterion("page_child_id <>", value, "pageChildId");
            return (Criteria) this;
        }

        public Criteria andPageChildIdGreaterThan(Integer value) {
            addCriterion("page_child_id >", value, "pageChildId");
            return (Criteria) this;
        }

        public Criteria andPageChildIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("page_child_id >=", value, "pageChildId");
            return (Criteria) this;
        }

        public Criteria andPageChildIdLessThan(Integer value) {
            addCriterion("page_child_id <", value, "pageChildId");
            return (Criteria) this;
        }

        public Criteria andPageChildIdLessThanOrEqualTo(Integer value) {
            addCriterion("page_child_id <=", value, "pageChildId");
            return (Criteria) this;
        }

        public Criteria andPageChildIdIn(List<Integer> values) {
            addCriterion("page_child_id in", values, "pageChildId");
            return (Criteria) this;
        }

        public Criteria andPageChildIdNotIn(List<Integer> values) {
            addCriterion("page_child_id not in", values, "pageChildId");
            return (Criteria) this;
        }

        public Criteria andPageChildIdBetween(Integer value1, Integer value2) {
            addCriterion("page_child_id between", value1, value2, "pageChildId");
            return (Criteria) this;
        }

        public Criteria andPageChildIdNotBetween(Integer value1, Integer value2) {
            addCriterion("page_child_id not between", value1, value2, "pageChildId");
            return (Criteria) this;
        }

        public Criteria andPageIdIsNull() {
            addCriterion("page_id is null");
            return (Criteria) this;
        }

        public Criteria andPageIdIsNotNull() {
            addCriterion("page_id is not null");
            return (Criteria) this;
        }

        public Criteria andPageIdEqualTo(Integer value) {
            addCriterion("page_id =", value, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageIdNotEqualTo(Integer value) {
            addCriterion("page_id <>", value, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageIdGreaterThan(Integer value) {
            addCriterion("page_id >", value, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("page_id >=", value, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageIdLessThan(Integer value) {
            addCriterion("page_id <", value, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageIdLessThanOrEqualTo(Integer value) {
            addCriterion("page_id <=", value, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageIdIn(List<Integer> values) {
            addCriterion("page_id in", values, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageIdNotIn(List<Integer> values) {
            addCriterion("page_id not in", values, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageIdBetween(Integer value1, Integer value2) {
            addCriterion("page_id between", value1, value2, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageIdNotBetween(Integer value1, Integer value2) {
            addCriterion("page_id not between", value1, value2, "pageId");
            return (Criteria) this;
        }

        public Criteria andPageChildUrlIsNull() {
            addCriterion("page_child_url is null");
            return (Criteria) this;
        }

        public Criteria andPageChildUrlIsNotNull() {
            addCriterion("page_child_url is not null");
            return (Criteria) this;
        }

        public Criteria andPageChildUrlEqualTo(String value) {
            addCriterion("page_child_url =", value, "pageChildUrl");
            return (Criteria) this;
        }

        public Criteria andPageChildUrlNotEqualTo(String value) {
            addCriterion("page_child_url <>", value, "pageChildUrl");
            return (Criteria) this;
        }

        public Criteria andPageChildUrlGreaterThan(String value) {
            addCriterion("page_child_url >", value, "pageChildUrl");
            return (Criteria) this;
        }

        public Criteria andPageChildUrlGreaterThanOrEqualTo(String value) {
            addCriterion("page_child_url >=", value, "pageChildUrl");
            return (Criteria) this;
        }

        public Criteria andPageChildUrlLessThan(String value) {
            addCriterion("page_child_url <", value, "pageChildUrl");
            return (Criteria) this;
        }

        public Criteria andPageChildUrlLessThanOrEqualTo(String value) {
            addCriterion("page_child_url <=", value, "pageChildUrl");
            return (Criteria) this;
        }

        public Criteria andPageChildUrlLike(String value) {
            addCriterion("page_child_url like", value, "pageChildUrl");
            return (Criteria) this;
        }

        public Criteria andPageChildUrlNotLike(String value) {
            addCriterion("page_child_url not like", value, "pageChildUrl");
            return (Criteria) this;
        }

        public Criteria andPageChildUrlIn(List<String> values) {
            addCriterion("page_child_url in", values, "pageChildUrl");
            return (Criteria) this;
        }

        public Criteria andPageChildUrlNotIn(List<String> values) {
            addCriterion("page_child_url not in", values, "pageChildUrl");
            return (Criteria) this;
        }

        public Criteria andPageChildUrlBetween(String value1, String value2) {
            addCriterion("page_child_url between", value1, value2, "pageChildUrl");
            return (Criteria) this;
        }

        public Criteria andPageChildUrlNotBetween(String value1, String value2) {
            addCriterion("page_child_url not between", value1, value2, "pageChildUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table page_child
     *
     do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table page_child
     *
    
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}