package com.myqq.entity.fangcha;

import java.util.ArrayList;
import java.util.List;

public class E2eAndKpiMeasuresExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e2e_and_kpi_measures
     *
    
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e2e_and_kpi_measures
     *
    
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e2e_and_kpi_measures
     *
    
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e2e_and_kpi_measures
     *
    
     */
    public E2eAndKpiMeasuresExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e2e_and_kpi_measures
     *
    
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e2e_and_kpi_measures
     *
    
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e2e_and_kpi_measures
     *
    
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e2e_and_kpi_measures
     *
    
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e2e_and_kpi_measures
     *
    
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e2e_and_kpi_measures
     *
    
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e2e_and_kpi_measures
     *
    
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e2e_and_kpi_measures
     *
    
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e2e_and_kpi_measures
     *
    
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e2e_and_kpi_measures
     *
    
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table e2e_and_kpi_measures
     *
    
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTimeMonthIsNull() {
            addCriterion("time_month is null");
            return (Criteria) this;
        }

        public Criteria andTimeMonthIsNotNull() {
            addCriterion("time_month is not null");
            return (Criteria) this;
        }

        public Criteria andTimeMonthEqualTo(Integer value) {
            addCriterion("time_month =", value, "timeMonth");
            return (Criteria) this;
        }

        public Criteria andTimeMonthNotEqualTo(Integer value) {
            addCriterion("time_month <>", value, "timeMonth");
            return (Criteria) this;
        }

        public Criteria andTimeMonthGreaterThan(Integer value) {
            addCriterion("time_month >", value, "timeMonth");
            return (Criteria) this;
        }

        public Criteria andTimeMonthGreaterThanOrEqualTo(Integer value) {
            addCriterion("time_month >=", value, "timeMonth");
            return (Criteria) this;
        }

        public Criteria andTimeMonthLessThan(Integer value) {
            addCriterion("time_month <", value, "timeMonth");
            return (Criteria) this;
        }

        public Criteria andTimeMonthLessThanOrEqualTo(Integer value) {
            addCriterion("time_month <=", value, "timeMonth");
            return (Criteria) this;
        }

        public Criteria andTimeMonthIn(List<Integer> values) {
            addCriterion("time_month in", values, "timeMonth");
            return (Criteria) this;
        }

        public Criteria andTimeMonthNotIn(List<Integer> values) {
            addCriterion("time_month not in", values, "timeMonth");
            return (Criteria) this;
        }

        public Criteria andTimeMonthBetween(Integer value1, Integer value2) {
            addCriterion("time_month between", value1, value2, "timeMonth");
            return (Criteria) this;
        }

        public Criteria andTimeMonthNotBetween(Integer value1, Integer value2) {
            addCriterion("time_month not between", value1, value2, "timeMonth");
            return (Criteria) this;
        }

        public Criteria andTimeWeekIsNull() {
            addCriterion("time_week is null");
            return (Criteria) this;
        }

        public Criteria andTimeWeekIsNotNull() {
            addCriterion("time_week is not null");
            return (Criteria) this;
        }

        public Criteria andTimeWeekEqualTo(Integer value) {
            addCriterion("time_week =", value, "timeWeek");
            return (Criteria) this;
        }

        public Criteria andTimeWeekNotEqualTo(Integer value) {
            addCriterion("time_week <>", value, "timeWeek");
            return (Criteria) this;
        }

        public Criteria andTimeWeekGreaterThan(Integer value) {
            addCriterion("time_week >", value, "timeWeek");
            return (Criteria) this;
        }

        public Criteria andTimeWeekGreaterThanOrEqualTo(Integer value) {
            addCriterion("time_week >=", value, "timeWeek");
            return (Criteria) this;
        }

        public Criteria andTimeWeekLessThan(Integer value) {
            addCriterion("time_week <", value, "timeWeek");
            return (Criteria) this;
        }

        public Criteria andTimeWeekLessThanOrEqualTo(Integer value) {
            addCriterion("time_week <=", value, "timeWeek");
            return (Criteria) this;
        }

        public Criteria andTimeWeekIn(List<Integer> values) {
            addCriterion("time_week in", values, "timeWeek");
            return (Criteria) this;
        }

        public Criteria andTimeWeekNotIn(List<Integer> values) {
            addCriterion("time_week not in", values, "timeWeek");
            return (Criteria) this;
        }

        public Criteria andTimeWeekBetween(Integer value1, Integer value2) {
            addCriterion("time_week between", value1, value2, "timeWeek");
            return (Criteria) this;
        }

        public Criteria andTimeWeekNotBetween(Integer value1, Integer value2) {
            addCriterion("time_week not between", value1, value2, "timeWeek");
            return (Criteria) this;
        }

        public Criteria andTimeHourIsNull() {
            addCriterion("time_hour is null");
            return (Criteria) this;
        }

        public Criteria andTimeHourIsNotNull() {
            addCriterion("time_hour is not null");
            return (Criteria) this;
        }

        public Criteria andTimeHourEqualTo(Integer value) {
            addCriterion("time_hour =", value, "timeHour");
            return (Criteria) this;
        }

        public Criteria andTimeHourNotEqualTo(Integer value) {
            addCriterion("time_hour <>", value, "timeHour");
            return (Criteria) this;
        }

        public Criteria andTimeHourGreaterThan(Integer value) {
            addCriterion("time_hour >", value, "timeHour");
            return (Criteria) this;
        }

        public Criteria andTimeHourGreaterThanOrEqualTo(Integer value) {
            addCriterion("time_hour >=", value, "timeHour");
            return (Criteria) this;
        }

        public Criteria andTimeHourLessThan(Integer value) {
            addCriterion("time_hour <", value, "timeHour");
            return (Criteria) this;
        }

        public Criteria andTimeHourLessThanOrEqualTo(Integer value) {
            addCriterion("time_hour <=", value, "timeHour");
            return (Criteria) this;
        }

        public Criteria andTimeHourIn(List<Integer> values) {
            addCriterion("time_hour in", values, "timeHour");
            return (Criteria) this;
        }

        public Criteria andTimeHourNotIn(List<Integer> values) {
            addCriterion("time_hour not in", values, "timeHour");
            return (Criteria) this;
        }

        public Criteria andTimeHourBetween(Integer value1, Integer value2) {
            addCriterion("time_hour between", value1, value2, "timeHour");
            return (Criteria) this;
        }

        public Criteria andTimeHourNotBetween(Integer value1, Integer value2) {
            addCriterion("time_hour not between", value1, value2, "timeHour");
            return (Criteria) this;
        }

        public Criteria andTimeUnitIsNull() {
            addCriterion("time_unit is null");
            return (Criteria) this;
        }

        public Criteria andTimeUnitIsNotNull() {
            addCriterion("time_unit is not null");
            return (Criteria) this;
        }

        public Criteria andTimeUnitEqualTo(String value) {
            addCriterion("time_unit =", value, "timeUnit");
            return (Criteria) this;
        }

        public Criteria andTimeUnitNotEqualTo(String value) {
            addCriterion("time_unit <>", value, "timeUnit");
            return (Criteria) this;
        }

        public Criteria andTimeUnitGreaterThan(String value) {
            addCriterion("time_unit >", value, "timeUnit");
            return (Criteria) this;
        }

        public Criteria andTimeUnitGreaterThanOrEqualTo(String value) {
            addCriterion("time_unit >=", value, "timeUnit");
            return (Criteria) this;
        }

        public Criteria andTimeUnitLessThan(String value) {
            addCriterion("time_unit <", value, "timeUnit");
            return (Criteria) this;
        }

        public Criteria andTimeUnitLessThanOrEqualTo(String value) {
            addCriterion("time_unit <=", value, "timeUnit");
            return (Criteria) this;
        }

        public Criteria andTimeUnitLike(String value) {
            addCriterion("time_unit like", value, "timeUnit");
            return (Criteria) this;
        }

        public Criteria andTimeUnitNotLike(String value) {
            addCriterion("time_unit not like", value, "timeUnit");
            return (Criteria) this;
        }

        public Criteria andTimeUnitIn(List<String> values) {
            addCriterion("time_unit in", values, "timeUnit");
            return (Criteria) this;
        }

        public Criteria andTimeUnitNotIn(List<String> values) {
            addCriterion("time_unit not in", values, "timeUnit");
            return (Criteria) this;
        }

        public Criteria andTimeUnitBetween(String value1, String value2) {
            addCriterion("time_unit between", value1, value2, "timeUnit");
            return (Criteria) this;
        }

        public Criteria andTimeUnitNotBetween(String value1, String value2) {
            addCriterion("time_unit not between", value1, value2, "timeUnit");
            return (Criteria) this;
        }

        public Criteria andKpiIdIsNull() {
            addCriterion("kpi_id is null");
            return (Criteria) this;
        }

        public Criteria andKpiIdIsNotNull() {
            addCriterion("kpi_id is not null");
            return (Criteria) this;
        }

        public Criteria andKpiIdEqualTo(Integer value) {
            addCriterion("kpi_id =", value, "kpiId");
            return (Criteria) this;
        }

        public Criteria andKpiIdNotEqualTo(Integer value) {
            addCriterion("kpi_id <>", value, "kpiId");
            return (Criteria) this;
        }

        public Criteria andKpiIdGreaterThan(Integer value) {
            addCriterion("kpi_id >", value, "kpiId");
            return (Criteria) this;
        }

        public Criteria andKpiIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("kpi_id >=", value, "kpiId");
            return (Criteria) this;
        }

        public Criteria andKpiIdLessThan(Integer value) {
            addCriterion("kpi_id <", value, "kpiId");
            return (Criteria) this;
        }

        public Criteria andKpiIdLessThanOrEqualTo(Integer value) {
            addCriterion("kpi_id <=", value, "kpiId");
            return (Criteria) this;
        }

        public Criteria andKpiIdIn(List<Integer> values) {
            addCriterion("kpi_id in", values, "kpiId");
            return (Criteria) this;
        }

        public Criteria andKpiIdNotIn(List<Integer> values) {
            addCriterion("kpi_id not in", values, "kpiId");
            return (Criteria) this;
        }

        public Criteria andKpiIdBetween(Integer value1, Integer value2) {
            addCriterion("kpi_id between", value1, value2, "kpiId");
            return (Criteria) this;
        }

        public Criteria andKpiIdNotBetween(Integer value1, Integer value2) {
            addCriterion("kpi_id not between", value1, value2, "kpiId");
            return (Criteria) this;
        }

        public Criteria andE2eIdIsNull() {
            addCriterion("e2e_id is null");
            return (Criteria) this;
        }

        public Criteria andE2eIdIsNotNull() {
            addCriterion("e2e_id is not null");
            return (Criteria) this;
        }

        public Criteria andE2eIdEqualTo(Integer value) {
            addCriterion("e2e_id =", value, "e2eId");
            return (Criteria) this;
        }

        public Criteria andE2eIdNotEqualTo(Integer value) {
            addCriterion("e2e_id <>", value, "e2eId");
            return (Criteria) this;
        }

        public Criteria andE2eIdGreaterThan(Integer value) {
            addCriterion("e2e_id >", value, "e2eId");
            return (Criteria) this;
        }

        public Criteria andE2eIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("e2e_id >=", value, "e2eId");
            return (Criteria) this;
        }

        public Criteria andE2eIdLessThan(Integer value) {
            addCriterion("e2e_id <", value, "e2eId");
            return (Criteria) this;
        }

        public Criteria andE2eIdLessThanOrEqualTo(Integer value) {
            addCriterion("e2e_id <=", value, "e2eId");
            return (Criteria) this;
        }

        public Criteria andE2eIdIn(List<Integer> values) {
            addCriterion("e2e_id in", values, "e2eId");
            return (Criteria) this;
        }

        public Criteria andE2eIdNotIn(List<Integer> values) {
            addCriterion("e2e_id not in", values, "e2eId");
            return (Criteria) this;
        }

        public Criteria andE2eIdBetween(Integer value1, Integer value2) {
            addCriterion("e2e_id between", value1, value2, "e2eId");
            return (Criteria) this;
        }

        public Criteria andE2eIdNotBetween(Integer value1, Integer value2) {
            addCriterion("e2e_id not between", value1, value2, "e2eId");
            return (Criteria) this;
        }

        public Criteria andSumCountIsNull() {
            addCriterion("sum_count is null");
            return (Criteria) this;
        }

        public Criteria andSumCountIsNotNull() {
            addCriterion("sum_count is not null");
            return (Criteria) this;
        }

        public Criteria andSumCountEqualTo(Integer value) {
            addCriterion("sum_count =", value, "sumCount");
            return (Criteria) this;
        }

        public Criteria andSumCountNotEqualTo(Integer value) {
            addCriterion("sum_count <>", value, "sumCount");
            return (Criteria) this;
        }

        public Criteria andSumCountGreaterThan(Integer value) {
            addCriterion("sum_count >", value, "sumCount");
            return (Criteria) this;
        }

        public Criteria andSumCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("sum_count >=", value, "sumCount");
            return (Criteria) this;
        }

        public Criteria andSumCountLessThan(Integer value) {
            addCriterion("sum_count <", value, "sumCount");
            return (Criteria) this;
        }

        public Criteria andSumCountLessThanOrEqualTo(Integer value) {
            addCriterion("sum_count <=", value, "sumCount");
            return (Criteria) this;
        }

        public Criteria andSumCountIn(List<Integer> values) {
            addCriterion("sum_count in", values, "sumCount");
            return (Criteria) this;
        }

        public Criteria andSumCountNotIn(List<Integer> values) {
            addCriterion("sum_count not in", values, "sumCount");
            return (Criteria) this;
        }

        public Criteria andSumCountBetween(Integer value1, Integer value2) {
            addCriterion("sum_count between", value1, value2, "sumCount");
            return (Criteria) this;
        }

        public Criteria andSumCountNotBetween(Integer value1, Integer value2) {
            addCriterion("sum_count not between", value1, value2, "sumCount");
            return (Criteria) this;
        }

        public Criteria andSumValueIsNull() {
            addCriterion("sum_value is null");
            return (Criteria) this;
        }

        public Criteria andSumValueIsNotNull() {
            addCriterion("sum_value is not null");
            return (Criteria) this;
        }

        public Criteria andSumValueEqualTo(Double value) {
            addCriterion("sum_value =", value, "sumValue");
            return (Criteria) this;
        }

        public Criteria andSumValueNotEqualTo(Double value) {
            addCriterion("sum_value <>", value, "sumValue");
            return (Criteria) this;
        }

        public Criteria andSumValueGreaterThan(Double value) {
            addCriterion("sum_value >", value, "sumValue");
            return (Criteria) this;
        }

        public Criteria andSumValueGreaterThanOrEqualTo(Double value) {
            addCriterion("sum_value >=", value, "sumValue");
            return (Criteria) this;
        }

        public Criteria andSumValueLessThan(Double value) {
            addCriterion("sum_value <", value, "sumValue");
            return (Criteria) this;
        }

        public Criteria andSumValueLessThanOrEqualTo(Double value) {
            addCriterion("sum_value <=", value, "sumValue");
            return (Criteria) this;
        }

        public Criteria andSumValueIn(List<Double> values) {
            addCriterion("sum_value in", values, "sumValue");
            return (Criteria) this;
        }

        public Criteria andSumValueNotIn(List<Double> values) {
            addCriterion("sum_value not in", values, "sumValue");
            return (Criteria) this;
        }

        public Criteria andSumValueBetween(Double value1, Double value2) {
            addCriterion("sum_value between", value1, value2, "sumValue");
            return (Criteria) this;
        }

        public Criteria andSumValueNotBetween(Double value1, Double value2) {
            addCriterion("sum_value not between", value1, value2, "sumValue");
            return (Criteria) this;
        }

        public Criteria andVarianceIsNull() {
            addCriterion("variance is null");
            return (Criteria) this;
        }

        public Criteria andVarianceIsNotNull() {
            addCriterion("variance is not null");
            return (Criteria) this;
        }

        public Criteria andVarianceEqualTo(Double value) {
            addCriterion("variance =", value, "variance");
            return (Criteria) this;
        }

        public Criteria andVarianceNotEqualTo(Double value) {
            addCriterion("variance <>", value, "variance");
            return (Criteria) this;
        }

        public Criteria andVarianceGreaterThan(Double value) {
            addCriterion("variance >", value, "variance");
            return (Criteria) this;
        }

        public Criteria andVarianceGreaterThanOrEqualTo(Double value) {
            addCriterion("variance >=", value, "variance");
            return (Criteria) this;
        }

        public Criteria andVarianceLessThan(Double value) {
            addCriterion("variance <", value, "variance");
            return (Criteria) this;
        }

        public Criteria andVarianceLessThanOrEqualTo(Double value) {
            addCriterion("variance <=", value, "variance");
            return (Criteria) this;
        }

        public Criteria andVarianceIn(List<Double> values) {
            addCriterion("variance in", values, "variance");
            return (Criteria) this;
        }

        public Criteria andVarianceNotIn(List<Double> values) {
            addCriterion("variance not in", values, "variance");
            return (Criteria) this;
        }

        public Criteria andVarianceBetween(Double value1, Double value2) {
            addCriterion("variance between", value1, value2, "variance");
            return (Criteria) this;
        }

        public Criteria andVarianceNotBetween(Double value1, Double value2) {
            addCriterion("variance not between", value1, value2, "variance");
            return (Criteria) this;
        }

        public Criteria andStandardDeviationIsNull() {
            addCriterion("standard_deviation is null");
            return (Criteria) this;
        }

        public Criteria andStandardDeviationIsNotNull() {
            addCriterion("standard_deviation is not null");
            return (Criteria) this;
        }

        public Criteria andStandardDeviationEqualTo(Double value) {
            addCriterion("standard_deviation =", value, "standardDeviation");
            return (Criteria) this;
        }

        public Criteria andStandardDeviationNotEqualTo(Double value) {
            addCriterion("standard_deviation <>", value, "standardDeviation");
            return (Criteria) this;
        }

        public Criteria andStandardDeviationGreaterThan(Double value) {
            addCriterion("standard_deviation >", value, "standardDeviation");
            return (Criteria) this;
        }

        public Criteria andStandardDeviationGreaterThanOrEqualTo(Double value) {
            addCriterion("standard_deviation >=", value, "standardDeviation");
            return (Criteria) this;
        }

        public Criteria andStandardDeviationLessThan(Double value) {
            addCriterion("standard_deviation <", value, "standardDeviation");
            return (Criteria) this;
        }

        public Criteria andStandardDeviationLessThanOrEqualTo(Double value) {
            addCriterion("standard_deviation <=", value, "standardDeviation");
            return (Criteria) this;
        }

        public Criteria andStandardDeviationIn(List<Double> values) {
            addCriterion("standard_deviation in", values, "standardDeviation");
            return (Criteria) this;
        }

        public Criteria andStandardDeviationNotIn(List<Double> values) {
            addCriterion("standard_deviation not in", values, "standardDeviation");
            return (Criteria) this;
        }

        public Criteria andStandardDeviationBetween(Double value1, Double value2) {
            addCriterion("standard_deviation between", value1, value2, "standardDeviation");
            return (Criteria) this;
        }

        public Criteria andStandardDeviationNotBetween(Double value1, Double value2) {
            addCriterion("standard_deviation not between", value1, value2, "standardDeviation");
            return (Criteria) this;
        }

        public Criteria andAvgIsNull() {
            addCriterion("avg is null");
            return (Criteria) this;
        }

        public Criteria andAvgIsNotNull() {
            addCriterion("avg is not null");
            return (Criteria) this;
        }

        public Criteria andAvgEqualTo(Double value) {
            addCriterion("avg =", value, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgNotEqualTo(Double value) {
            addCriterion("avg <>", value, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgGreaterThan(Double value) {
            addCriterion("avg >", value, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgGreaterThanOrEqualTo(Double value) {
            addCriterion("avg >=", value, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgLessThan(Double value) {
            addCriterion("avg <", value, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgLessThanOrEqualTo(Double value) {
            addCriterion("avg <=", value, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgIn(List<Double> values) {
            addCriterion("avg in", values, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgNotIn(List<Double> values) {
            addCriterion("avg not in", values, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgBetween(Double value1, Double value2) {
            addCriterion("avg between", value1, value2, "avg");
            return (Criteria) this;
        }

        public Criteria andAvgNotBetween(Double value1, Double value2) {
            addCriterion("avg not between", value1, value2, "avg");
            return (Criteria) this;
        }

        public Criteria andCvIsNull() {
            addCriterion("cv is null");
            return (Criteria) this;
        }

        public Criteria andCvIsNotNull() {
            addCriterion("cv is not null");
            return (Criteria) this;
        }

        public Criteria andCvEqualTo(Double value) {
            addCriterion("cv =", value, "cv");
            return (Criteria) this;
        }

        public Criteria andCvNotEqualTo(Double value) {
            addCriterion("cv <>", value, "cv");
            return (Criteria) this;
        }

        public Criteria andCvGreaterThan(Double value) {
            addCriterion("cv >", value, "cv");
            return (Criteria) this;
        }

        public Criteria andCvGreaterThanOrEqualTo(Double value) {
            addCriterion("cv >=", value, "cv");
            return (Criteria) this;
        }

        public Criteria andCvLessThan(Double value) {
            addCriterion("cv <", value, "cv");
            return (Criteria) this;
        }

        public Criteria andCvLessThanOrEqualTo(Double value) {
            addCriterion("cv <=", value, "cv");
            return (Criteria) this;
        }

        public Criteria andCvIn(List<Double> values) {
            addCriterion("cv in", values, "cv");
            return (Criteria) this;
        }

        public Criteria andCvNotIn(List<Double> values) {
            addCriterion("cv not in", values, "cv");
            return (Criteria) this;
        }

        public Criteria andCvBetween(Double value1, Double value2) {
            addCriterion("cv between", value1, value2, "cv");
            return (Criteria) this;
        }

        public Criteria andCvNotBetween(Double value1, Double value2) {
            addCriterion("cv not between", value1, value2, "cv");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table e2e_and_kpi_measures
     *
     do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table e2e_and_kpi_measures
     *
    
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}